package io.waypoint.core;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Byte-for-byte parity with Lucene's {@code SmallFloat}, asserted against a
 * golden table.
 *
 * <p>The table below was generated by running Lucene 10.5.1's own
 * {@code SmallFloat.byte4ToInt} over all 256 byte values, and is committed so
 * this test can live in {@code core}, which has no dependencies -- including no
 * test dependency on Lucene. {@code bench} verifies the same property the other
 * way round, end to end, by asserting score agreement on documents whose
 * lengths sweep the entire quantisation range.
 *
 * <p>This matters more than it looks. Document length is stored in one byte, so
 * a length of 256 and a length of 264 are the same number as far as BM25 is
 * concerned. If our bucket boundaries were off by one anywhere, long documents
 * would score subtly differently from Lucene's and the "same ranking" claim
 * would be false in exactly the cases nobody checks.
 */
class SmallFloatTest {

  /** Lucene 10.5.1: {@code SmallFloat.byte4ToInt((byte) i)} for i in 0..255. */
  private static final int[] GOLDEN_BYTE4_TO_INT = {
    0, 1, 2, 3, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23,
    24, 25, 26, 27, 28, 29, 30, 31,
    32, 33, 34, 35, 36, 37, 38, 39,
    40, 42, 44, 46, 48, 50, 52, 54,
    56, 60, 64, 68, 72, 76, 80, 84,
    88, 96, 104, 112, 120, 128, 136, 144,
    152, 168, 184, 200, 216, 232, 248, 264,
    280, 312, 344, 376, 408, 440, 472, 504,
    536, 600, 664, 728, 792, 856, 920, 984,
    1048, 1176, 1304, 1432, 1560, 1688, 1816, 1944,
    2072, 2328, 2584, 2840, 3096, 3352, 3608, 3864,
    4120, 4632, 5144, 5656, 6168, 6680, 7192, 7704,
    8216, 9240, 10264, 11288, 12312, 13336, 14360, 15384,
    16408, 18456, 20504, 22552, 24600, 26648, 28696, 30744,
    32792, 36888, 40984, 45080, 49176, 53272, 57368, 61464,
    65560, 73752, 81944, 90136, 98328, 106520, 114712, 122904,
    131096, 147480, 163864, 180248, 196632, 213016, 229400, 245784,
    262168, 294936, 327704, 360472, 393240, 426008, 458776, 491544,
    524312, 589848, 655384, 720920, 786456, 851992, 917528, 983064,
    1048600, 1179672, 1310744, 1441816, 1572888, 1703960, 1835032, 1966104,
    2097176, 2359320, 2621464, 2883608, 3145752, 3407896, 3670040, 3932184,
    4194328, 4718616, 5242904, 5767192, 6291480, 6815768, 7340056, 7864344,
    8388632, 9437208, 10485784, 11534360, 12582936, 13631512, 14680088, 15728664,
    16777240, 18874392, 20971544, 23068696, 25165848, 27263000, 29360152, 31457304,
    33554456, 37748760, 41943064, 46137368, 50331672, 54525976, 58720280, 62914584,
    67108888, 75497496, 83886104, 92274712, 100663320, 109051928, 117440536, 125829144,
    134217752, 150994968, 167772184, 184549400, 201326616, 218103832, 234881048, 251658264,
    268435480, 301989912, 335544344, 369098776, 402653208, 436207640, 469762072, 503316504,
    536870936, 603979800, 671088664, 738197528, 805306392, 872415256, 939524120, 1006632984,
    1073741848, 1207959576, 1342177304, 1476395032, 1610612760, 1744830488, 1879048216, 2013265944,
  };

  /** Lucene 10.5.1: {@code {length, intToByte4(length) & 0xFF}}. */
  private static final int[][] GOLDEN_INT_TO_BYTE4 = {
    {0, 0}, {1, 1}, {2, 2}, {3, 3}, {7, 7}, {8, 8}, {15, 15}, {16, 16},
    {17, 17}, {31, 31}, {32, 32}, {63, 49}, {64, 50}, {127, 60}, {128, 61},
    {255, 70}, {256, 70}, {511, 79}, {512, 79}, {1023, 87}, {1024, 87},
    {2047, 95}, {4095, 103}, {8191, 111}, {65535, 135}, {1000000, 167},
    {Integer.MAX_VALUE, 255},
  };

  @Test
  void decodesEveryByteExactlyAsLuceneDoes() {
    for (int i = 0; i < 256; i++) {
      assertEquals(
          GOLDEN_BYTE4_TO_INT[i], SmallFloat.byte4ToInt((byte) i), "byte4ToInt(" + i + ")");
    }
  }

  @Test
  void encodesLengthsExactlyAsLuceneDoes() {
    for (int[] pair : GOLDEN_INT_TO_BYTE4) {
      assertEquals(
          pair[1], SmallFloat.intToByte4(pair[0]) & 0xFF, "intToByte4(" + pair[0] + ")");
    }
  }

  /** The encoding has to be non-decreasing, or longer documents could outscore shorter ones. */
  @Test
  void encodingIsMonotonic() {
    int previous = -1;
    for (int len = 0; len < 200_000; len++) {
      int encoded = SmallFloat.intToByte4(len) & 0xFF;
      assertTrue(encoded >= previous, "intToByte4 decreased at length " + len);
      previous = encoded;
    }
  }

  /** Lengths below the first quantisation step must survive a round trip exactly. */
  @Test
  void smallLengthsRoundTripExactly() {
    for (int len = 0; len < 40; len++) {
      assertEquals(len, SmallFloat.byte4ToInt(SmallFloat.intToByte4(len)));
    }
  }

  @Test
  void decodedLengthIsNeverGreaterThanTheEncodedOne() {
    for (int len = 0; len < 500_000; len += 7) {
      assertTrue(
          SmallFloat.byte4ToInt(SmallFloat.intToByte4(len)) <= len,
          "quantisation rounded up at " + len);
    }
  }
}
